### ISSUE TITLE
可以不用做成插件

### ISSUE THREAD

**Issue by ylxdzsw** [liu946/CSTool_Pingjiao#1]
利用`javascript:`可以把它做成一个链接，添加到收藏夹里就行了，到时候再评教页面点击收藏就行。  
你可以把这个链接做成按钮放在github page上，用户只需要把这个按钮拖到收藏栏，然后在评教页面点击，比下载插件还方便  
safari好像禁止了`javascript:`链接，但是chrome没有

**Comment by liu946** [comment]
我看见百度云是这样做的。建议很好，这样方便很多。
